services:
  - type: web
    name: kashmir-disha-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
